Cart functionality/sone
fullstack-ecommerce/ecommerce-site pull request #26
Opened 2020-12-09 04:23 UTC by SoneThaya

2020-12-09 04:31 UTC, anthonyamaro15 commented on client/src/state/actions/cartActions.js
> +  localStorage.setItem("cartItems", JSON.stringify(getState().cart.cartItems));
I'm a bit confused about why you are saving cart data in localStorage?

2020-12-09 04:32 UTC, anthonyamaro15 commented on client/src/store.js
> +  : [];
I don't think you need to save this data to localStorage you can just get it from the backend whenever a user log in

2020-12-09 04:35 UTC, anthonyamaro15 requested changes
I left a few comments

2020-12-10 00:09 UTC, closed without merging

2020-12-10 00:09 UTC, SoneThaya commented
edited the code, will create a new pull request